// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using sciendo.preferences.service.Logic;
//
//    var temperatures = Temperatures.FromJson(jsonString);

namespace sciendo.preferences.service.Logic
{
    using System;

    using System.Globalization;
    using System.Text.Json;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using JsonConverter = Newtonsoft.Json.JsonConverter;
    using JsonConverterAttribute = Newtonsoft.Json.JsonConverterAttribute;

    public partial class Temperatures
    {
        [JsonProperty("similarartists")]
        public SimilarArtists SimilarArtists { get; set; }
    }

    public partial class SimilarArtists
    {
        [JsonProperty("artist")]
        public Artist[] Artist { get; set; }

        [JsonProperty("@attr")]
        public Attr Attr { get; set; }
    }

    public partial class Artist
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("mbid")]
        public Guid Mbid { get; set; }

        [JsonProperty("match")]
        public string Match { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("image")]
        public Image[] Image { get; set; }

        [JsonProperty("streamable")]
        public string Streamable { get; set; }
    }

    public partial class Image
    {
        [JsonProperty("#text")]
        public Uri Text { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }
    }

    public partial class Attr
    {
        [JsonProperty("artist")]
        public string Artist { get; set; }
    }

    public partial class Temperatures
    {
        public static Temperatures FromJson(string json) => JsonConvert.DeserializeObject<Temperatures>(json);
    }

}
